### ISSUE TITLE
can I map contig sequence to the graph ?

### ISSUE THREAD

**Issue by zhoudreames** [algbio/GraphChainer#3]
i want to map the contig to my graph,but there is error when running this code:
GraphChainer -f contig.fa -g chr16_parm_2.gfa -a chr16Vshap1.gam -t 100

this error shows in blow:
GraphChainer Branch master commit 403cff6d1f4a385126a25199f00f68e24f28db7f 2022-01-05 10:59:13 +0200
GraphChainer Branch master commit 403cff6d1f4a385126a25199f00f68e24f28db7f 2022-01-05 10:59:13 +0200
Co-linear chaining on splits=(35,35,10000)
Load graph from chr16_parm_2.gfa
Build alignment graph
798 original nodes, 399 in one strand
1715331 split nodes, 857665 in one strand
0 ambiguous split nodes
109732932 base pairs (total characters), 54866466 in one strand
1716013 edges, 858006 in one strand
773 nodes with in-degree >= 2, 386 in one strand
Build MPC Index
2 connected components
cid = 0 path #0 : 35295 35295 822364
cid = 0 path #0 : 26911 26911 795453
cid = 0 path #0 : 822 822 794631
cid = 0 path #0 : 821 821 793810
cid = 0 path #0 : 821 821 792989
cid = 0 path #0 : 820 820 792169
cid = 0 path #0 : 820 820 791349
cid = 0 path #0 : 820 820 790529
cid = 0 path #0 : 820 820 789709
cid = 0 path #0 : 820 820 788889
cid = 0 path #0 : 819 819 788070
cid = 0 path #0 : 819 819 787251
cid = 0 path #0 : 819 819 786432
cid = 0 path #0 : 816 816 785616
cid = 0 path #0 : 816 816 784800
cid = 0 path #0 : 816 816 783984
cid = 0 path #0 : 9813 778 783206
cid = 0 path #0 : 723 723 782483
cid = 0 path #0 : 723 723 781760
cid = 0 path #0 : 718 718 781042
cid = 0 path #0 : 700 700 780342
cid = 0 path #0 : 700 700 779642
cid = 0 path #0 : 681 681 778961
cid = 0 path #0 : 681 681 778280
cid = 0 path #0 : 657 657 777623
cid = 0 path #0 : 657 657 776966
cid = 0 path #0 : 641 641 776325
cid = 0 path #0 : 617 617 775708
cid = 0 path #0 : 617 617 775091
cid = 0 path #0 : 536 536 774555
cid = 0 path #0 : 527 527 774028
cid = 0 path #0 : 509 509 773519
cid = 0 path #0 : 507 507 773012
cid = 0 path #0 : 507 507 772505
cid = 0 path #0 : 500 500 772005
cid = 0 path #0 : 500 500 771505
cid = 0 path #0 : 484 484 771021
cid = 0 path #0 : 484 484 770537
cid = 0 path #0 : 476 476 770061
cid = 0 path #0 : 476 476 769585
cid = 0 path #0 : 472 472 769113
cid = 0 path #0 : 472 472 768641
cid = 0 path #0 : 467 467 768174
cid = 0 path #0 : 467 467 767707
cid = 0 path #0 : 464 464 767243
cid = 0 path #0 : 464 464 766779
cid = 0 path #0 : 461 461 766318
cid = 0 path #0 : 461 461 765857
cid = 0 path #0 : 461 461 765396
cid = 0 path #0 : 459 459 764937
cid = 0 path #0 : 458 458 764479
cid = 0 path #0 : 458 458 764021
cid = 0 path #0 : 453 453 763568
cid = 0 path #0 : 447 447 763121
cid = 0 path #0 : 447 447 762674
cid = 0 path #0 : 446 446 762228
cid = 0 path #0 : 446 446 761782
cid = 0 path #0 : 446 446 761336
cid = 0 path #0 : 446 446 760890
cid = 0 path #0 : 442 442 760448
cid = 0 path #0 : 442 442 760006
cid = 0 path #0 : 442 442 759564
cid = 0 path #0 : 442 442 759122
cid = 0 path #0 : 432 432 758690
cid = 0 path #0 : 423 423 758267
cid = 0 path #0 : 423 423 757844
cid = 0 path #0 : 422 422 757422
cid = 0 path #0 : 422 422 757000
cid = 0 path #0 : 411 411 756589
cid = 0 path #0 : 411 411 756178
cid = 0 path #0 : 410 410 755768
cid = 0 path #0 : 403 403 755365
cid = 0 path #0 : 397 397 754968
cid = 0 path #0 : 397 397 754571
cid = 0 path #0 : 392 392 754179
cid = 0 path #0 : 392 392 753787
cid = 0 path #0 : 391 391 753396
cid = 0 path #0 : 388 388 753008
cid = 0 path #0 : 388 388 752620
cid = 0 path #0 : 385 385 752235
cid = 0 path #0 : 385 385 751850
cid = 0 path #0 : 384 384 751466
cid = 0 path #0 : 384 384 751082
cid = 0 path #0 : 384 384 750698
cid = 0 path #0 : 383 383 750315
cid = 0 path #0 : 381 381 749934
cid = 0 path #0 : 381 381 749553
cid = 0 path #0 : 381 381 749172
cid = 0 path #0 : 381 381 748791
cid = 0 path #0 : 380 380 748411
cid = 0 path #0 : 380 380 748031
cid = 0 path #0 : 380 380 747651
cid = 0 path #0 : 380 380 747271
cid = 0 path #0 : 379 379 746892
cid = 0 path #0 : 379 379 746513
cid = 0 path #0 : 378 378 746135
cid = 0 path #0 : 376 376 745759
cid = 0 path #0 : 376 376 745383
cid = 0 path #0 : 375 375 745008
cid = 0 path #0 : 375 375 744633
cid = 0 path #0 : 374 374 744259
cid = 0 path #0 : 374 374 743885
cid = 0 path #0 : 373 373 743512
cid = 0 path #0 : 373 373 743139
cid = 0 path #0 : 371 371 742768
cid = 0 path #0 : 371 371 742397
cid = 0 path #0 : 370 370 742027
cid = 0 path #0 : 370 370 741657
cid = 0 path #0 : 370 370 741287
cid = 0 path #0 : 370 370 740917
cid = 0 path #0 : 370 370 740547
cid = 0 path #0 : 370 370 740177
cid = 0 path #0 : 370 370 739807
cid = 0 path #0 : 366 366 739441
cid = 0 path #0 : 364 364 739077
cid = 0 path #0 : 364 364 738713
cid = 0 path #0 : 364 364 738349
cid = 0 path #0 : 362 362 737987
cid = 0 path #0 : 362 362 737625
cid = 0 path #0 : 358 358 737267
cid = 0 path #0 : 358 358 736909
cid = 0 path #0 : 357 357 736552
cid = 0 path #0 : 357 357 736195
cid = 0 path #0 : 356 356 735839
cid = 0 path #0 : 356 356 735483
cid = 0 path #0 : 353 353 735130
cid = 0 path #0 : 353 353 734777
cid = 0 path #0 : 351 351 734426
cid = 0 path #0 : 351 351 734075
cid = 0 path #0 : 350 350 733725
cid = 0 path #0 : 350 350 733375
cid = 0 path #0 : 349 349 733026
cid = 0 path #0 : 349 349 732677
cid = 0 path #0 : 349 349 732328
cid = 0 path #0 : 347 347 731981
cid = 0 path #0 : 347 347 731634
cid = 0 path #0 : 345 345 731289
cid = 0 path #0 : 340 340 730949
cid = 0 path #0 : 340 340 730609
cid = 0 path #0 : 340 340 730269
cid = 0 path #0 : 338 338 729931
cid = 0 path #0 : 338 338 729593
cid = 0 path #0 : 338 338 729255
cid = 0 path #0 : 336 336 728919
cid = 0 path #0 : 336 336 728583
cid = 0 path #0 : 331 331 728252
cid = 0 path #0 : 331 331 727921
cid = 0 path #0 : 330 330 727591
cid = 0 path #0 : 330 330 727261
cid = 0 path #0 : 326 326 726935
cid = 0 path #0 : 326 326 726609
cid = 0 path #0 : 325 325 726284
cid = 0 path #0 : 325 325 725959
cid = 0 path #0 : 325 325 725634
cid = 0 path #0 : 324 324 725310
cid = 0 path #0 : 324 324 724986
cid = 0 path #0 : 324 324 724662
cid = 0 path #0 : 324 324 724338
cid = 0 path #0 : 323 323 724015
cid = 0 path #0 : 323 323 723692
cid = 0 path #0 : 322 322 723370
cid = 0 path #0 : 322 322 723048
cid = 0 path #0 : 317 317 722731
cid = 0 path #0 : 317 317 722414
cid = 0 path #0 : 313 313 722101
cid = 0 path #0 : 313 313 721788
cid = 0 path #0 : 312 312 721476
cid = 0 path #0 : 312 312 721164
cid = 0 path #0 : 311 311 720853
cid = 0 path #0 : 311 311 720542
cid = 0 path #0 : 311 311 720231
cid = 0 path #0 : 310 310 719921
cid = 0 path #0 : 310 310 719611
cid = 0 path #0 : 310 310 719301
cid = 0 path #0 : 310 310 718991
cid = 0 path #0 : 309 309 718682
cid = 0 path #0 : 309 309 718373
cid = 0 path #0 : 307 307 718066
cid = 0 path #0 : 307 307 717759
cid = 0 path #0 : 306 306 717453
cid = 0 path #0 : 306 306 717147
cid = 0 path #0 : 303 303 716844
cid = 0 path #0 : 303 303 716541
cid = 0 path #0 : 302 302 716239
cid = 0 path #0 : 302 302 715937
cid = 0 path #0 : 296 296 715641
cid = 0 path #0 : 296 296 715345
cid = 0 path #0 : 296 296 715049
cid = 0 path #0 : 296 296 714753
cid = 0 path #0 : 295 295 714458
cid = 0 path #0 : 295 295 714163
cid = 0 path #0 : 295 295 713868
cid = 0 path #0 : 295 295 713573
cid = 0 path #0 : 294 294 713279
cid = 0 path #0 : 293 293 712986
cid = 0 path #0 : 293 293 712693
cid = 0 path #0 : 293 293 712400
cid = 0 path #0 : 293 293 712107
cid = 0 path #0 : 289 289 711818
cid = 0 path #0 : 289 289 711529
cid = 0 path #0 : 289 289 711240
cid = 0 path #0 : 289 289 710951
cid = 0 path #0 : 289 289 710662
cid = 0 path #0 : 287 287 710375
cid = 0 path #0 : 287 287 710088
cid = 0 path #0 : 287 287 709801
cid = 0 path #0 : 284 284 709517
cid = 0 path #0 : 284 284 709233
cid = 0 path #0 : 282 282 708951
cid = 0 path #0 : 282 282 708669
cid = 0 path #0 : 282 282 708387
cid = 0 path #0 : 282 282 708105
cid = 0 path #0 : 281 281 707824
cid = 0 path #0 : 281 281 707543
cid = 0 path #0 : 280 280 707263
cid = 0 path #0 : 280 280 706983
cid = 0 path #0 : 280 280 706703
cid = 0 path #0 : 280 280 706423
cid = 0 path #0 : 280 280 706143
cid = 0 path #0 : 277 277 705866
cid = 0 path #0 : 277 277 705589
cid = 0 path #0 : 273 273 705316
cid = 0 path #0 : 273 273 705043
cid = 0 path #0 : 272 272 704771
cid = 0 path #0 : 272 272 704499
cid = 0 path #0 : 272 272 704227
cid = 0 path #0 : 272 272 703955
cid = 0 path #0 : 266 266 703689
cid = 0 path #0 : 266 266 703423
cid = 0 path #0 : 263 263 703160
cid = 0 path #0 : 263 263 702897
cid = 0 path #0 : 263 263 702634
cid = 0 path #0 : 263 263 702371
cid = 0 path #0 : 263 263 702108
cid = 0 path #0 : 262 262 701846
cid = 0 path #0 : 262 262 701584
cid = 0 path #0 : 260 260 701324
cid = 0 path #0 : 260 260 701064
cid = 0 path #0 : 259 259 700805
cid = 0 path #0 : 259 259 700546
cid = 0 path #0 : 259 259 700287
cid = 0 path #0 : 259 259 700028
cid = 0 path #0 : 257 257 699771
cid = 0 path #0 : 257 257 699514
cid = 0 path #0 : 257 257 699257
cid = 0 path #0 : 257 257 699000
cid = 0 path #0 : 256 256 698744
cid = 0 path #0 : 254 254 698490
cid = 0 path #0 : 254 254 698236
cid = 0 path #0 : 254 254 697982
cid = 0 path #0 : 254 254 697728
cid = 0 path #0 : 254 254 697474
cid = 0 path #0 : 251 251 697223
cid = 0 path #0 : 247 247 696976
cid = 0 path #0 : 247 247 696729
cid = 0 path #0 : 247 247 696482
cid = 0 path #0 : 247 247 696235
cid = 0 path #0 : 242 242 695993
cid = 0 path #0 : 232 232 695761
cid = 0 path #0 : 232 232 695529
cid = 0 path #0 : 231 231 695298
cid = 0 path #0 : 231 231 695067
cid = 0 path #0 : 231 231 694836
cid = 0 path #0 : 231 231 694605
cid = 0 path #0 : 231 231 694374
cid = 0 path #0 : 227 227 694147
cid = 0 path #0 : 224 224 693923
cid = 0 path #0 : 224 224 693699
cid = 0 path #0 : 220 220 693479
cid = 0 path #0 : 220 220 693259
cid = 0 path #0 : 216 216 693043
cid = 0 path #0 : 216 216 692827
cid = 0 path #0 : 212 212 692615
cid = 0 path #0 : 209 209 692406
cid = 0 path #0 : 209 209 692197
cid = 0 path #0 : 209 209 691988
cid = 0 path #0 : 209 209 691779
cid = 0 path #0 : 197 197 691582
cid = 0 path #0 : 197 197 691385
cid = 0 path #0 : 187 187 691198
cid = 0 path #0 : 186 186 691012
cid = 0 path #0 : 186 186 690826
Signal 11. Read: X��W��qe�. Seed: 0+,0,0,0
can you help me? thank~

**Comment by elarielcl** [comment]
Hello @zhoudreames. Thanks for raising this issue, it looks like the input sequence graph you are using has directed cycles. And the current version of GraphChainer does not support this class of graphs at this point.

We just added a more meaningful error message for this case. 

You can run the latest commit of GraphChainer and see if you get the message:
"The input sequence graph has a directed cycle.
The current version of GraphChainer only supports DAGs." 
to see if this is the case.
